package testTable;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javafx.scene.paint.Color.color;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cgntuser
 */
 import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

public class epilogi1 extends javax.swing.JFrame {

    /**
     * Creates new form epilogi
     */
    Connection con;//=null
    ResultSet rs=null;
    PreparedStatement pst=null;
    String username;//value for new cnstructor
    ArrayList<javax.swing.JTextField> list = new ArrayList<javax.swing.JTextField>();
    ArrayList<javax.swing.JLabel> LabelList= new ArrayList<javax.swing.JLabel>();
	 
    public epilogi1() {
        initComponents();
        con=SqlConnect.ConnectDB();
		//Αλλαγή & δημιουργια εμφάνισης Details στο menu bar
        jMenuItemNPV.setToolTipText(""
                + "<html>"
                + "<head>"
                + "h3{color:white;}"
                + "<style>"
                + "h4  {color: white;}"
                + ""
                + "</style>"
                + "</head>"
                + ""
                + "<body style=\"background-color:rgb(37, 34, 34)\">"
                + "<h4>Μετράει το πλεόνασμα ή την έλλειψη ταμειακών ροών σε σχέση με το κόστος κεφαλαίων που χρησιμοποιήθηκαν για μία επένδυση.</h4>"
                + "<h4> Τα πεδία εισόδου είναι το αρχικό κόστος, το επιτόκιο, καθώς και το πιθανό κέρδος των επόμενων χρόνων.</h4>"
                + "</body>"
                + ""
                + "</html>"
                + "");         
    }//epilogi
    
    public epilogi1(User user){//apo User.java
        this.setResizable(false);
        username=user.getUsername();
        initComponents();
    }
    
    private void table_update() {
        
        
    }
    epilogi1(String u) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenu3 = new javax.swing.JMenu();
		
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("riksmarl.sqlitePU").createEntityManager();
		testQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Test t WHERE t.username= :username").setParameter("username", username);
        //testQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Test t WHERE t.username = :username");
        testList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : testQuery.getResultList();
        select = new javax.swing.JPanel();
        Details = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        NPV = new javax.swing.JLabel();
        paybackPeriod = new javax.swing.JLabel();
        function3 = new javax.swing.JLabel();
        basicDetailsNPV = new javax.swing.JPanel();
        moreDetailsNPV = new javax.swing.JPanel();
        basicSeparator1 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        basicDetailsPP = new javax.swing.JPanel();
        basicDetails = new javax.swing.JPanel();
        moreDetailsPP = new javax.swing.JPanel();
        moreDetails = new javax.swing.JPanel();
        npvInsidePanel = new javax.swing.JPanel();
        resultButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        result = new java.awt.TextField();
        arxkostos = new java.awt.TextField();
        label4 = new java.awt.Label();
        jSeparator6 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        epitokio = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        xronia = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        kerdos = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabelTitle = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        SecondInvestment = new javax.swing.JPanel();
        label5 = new java.awt.Label();
        label2 = new java.awt.Label();
        epitokio1 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        arxkostos1 = new java.awt.TextField();
        arxkostos2 = new java.awt.TextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        comparison = new javax.swing.JCheckBox();
        SecondResult = new javax.swing.JPanel();
        resultButton2 = new javax.swing.JButton();
        result1 = new java.awt.TextField();
        jPanel5 = new javax.swing.JPanel();
        jLabelPaybackPeriodTEST = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNPV = new javax.swing.JMenuItem();
        jMenuItemPP = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemNPVprevious = new javax.swing.JMenuItem();
        jMenuItemPPprevious = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        select.setBackground(new java.awt.Color(37, 34, 34));
        select.setLayout(new java.awt.CardLayout());

        NPV.setText("Καθαρή Παρούσα Αξία");

        paybackPeriod.setText("Περίοδος Επανείσπραξης");

        function3.setText("Function 3 bfjkbfkjdbskjdhijhajnfjihejsa");

        javax.swing.GroupLayout basicDetailsNPVLayout = new javax.swing.GroupLayout(basicDetailsNPV);
        basicDetailsNPV.setLayout(basicDetailsNPVLayout);
        basicDetailsNPVLayout.setHorizontalGroup(
            basicDetailsNPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        basicDetailsNPVLayout.setVerticalGroup(
            basicDetailsNPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout moreDetailsNPVLayout = new javax.swing.GroupLayout(moreDetailsNPV);
        moreDetailsNPV.setLayout(moreDetailsNPVLayout);
        moreDetailsNPVLayout.setHorizontalGroup(
            moreDetailsNPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        moreDetailsNPVLayout.setVerticalGroup(
            moreDetailsNPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        basicSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        basicSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        basicSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout basicDetailsPPLayout = new javax.swing.GroupLayout(basicDetailsPP);
        basicDetailsPP.setLayout(basicDetailsPPLayout);
        basicDetailsPPLayout.setHorizontalGroup(
            basicDetailsPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        basicDetailsPPLayout.setVerticalGroup(
            basicDetailsPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout basicDetailsLayout = new javax.swing.GroupLayout(basicDetails);
        basicDetails.setLayout(basicDetailsLayout);
        basicDetailsLayout.setHorizontalGroup(
            basicDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        basicDetailsLayout.setVerticalGroup(
            basicDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout moreDetailsPPLayout = new javax.swing.GroupLayout(moreDetailsPP);
        moreDetailsPP.setLayout(moreDetailsPPLayout);
        moreDetailsPPLayout.setHorizontalGroup(
            moreDetailsPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        moreDetailsPPLayout.setVerticalGroup(
            moreDetailsPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout moreDetailsLayout = new javax.swing.GroupLayout(moreDetails);
        moreDetails.setLayout(moreDetailsLayout);
        moreDetailsLayout.setHorizontalGroup(
            moreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        moreDetailsLayout.setVerticalGroup(
            moreDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(NPV, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addComponent(paybackPeriod)
                        .addGap(82, 82, 82))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(moreDetailsNPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(basicDetailsNPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(basicSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(moreDetailsPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(basicDetailsPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(moreDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(basicDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(function3)
                        .addGap(53, 53, 53))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NPV)
                    .addComponent(paybackPeriod)
                    .addComponent(function3))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(basicSeparator1)
                    .addComponent(basicDetailsNPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basicDetailsPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basicDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moreDetailsNPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moreDetailsPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moreDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DetailsLayout = new javax.swing.GroupLayout(Details);
        Details.setLayout(DetailsLayout);
        DetailsLayout.setHorizontalGroup(
            DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DetailsLayout.setVerticalGroup(
            DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        select.add(Details, "card5");

        npvInsidePanel.setBackground(new java.awt.Color(37, 34, 34));
        npvInsidePanel.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N

        resultButton1.setBackground(new java.awt.Color(34, 34, 37));
        resultButton1.setFont(new java.awt.Font("Book Antiqua", 1, 11)); // NOI18N
        resultButton1.setForeground(new java.awt.Color(255, 255, 255));
        resultButton1.setText("Υπολόγισε");
        resultButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        resultButton1.setBorderPainted(false);
        resultButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        resultButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButton1ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Χρόνος:");

        result.setBackground(new java.awt.Color(37, 34, 34));
        result.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        result.setForeground(new java.awt.Color(255, 255, 255));

        arxkostos.setBackground(new java.awt.Color(37, 34, 34));
        arxkostos.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        arxkostos.setForeground(new java.awt.Color(255, 255, 255));
        arxkostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arxkostosActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Αρχικό Κόστος:");

        jComboBox1.setBackground(new java.awt.Color(37, 34, 34));
        jComboBox1.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        jComboBox1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBox1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(37, 34, 34));

        epitokio.setBackground(new java.awt.Color(37, 34, 34));
        epitokio.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        epitokio.setForeground(new java.awt.Color(255, 255, 255));
        epitokio.setText("Επιτόκιο:");

        jTextField1.setBackground(new java.awt.Color(37, 34, 34));
        jTextField1.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setBackground(new java.awt.Color(37, 34, 34));
        jLabel17.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Εκτιμώμενο Κέρδος:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(epitokio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(epitokio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        xronia.setBackground(new java.awt.Color(37, 34, 34));
        xronia.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1ο έτος:");

        kerdos.setBackground(new java.awt.Color(37, 34, 34));
        kerdos.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        kerdos.setForeground(new java.awt.Color(255, 255, 255));

        jTextField3.setBackground(new java.awt.Color(37, 34, 34));
        jTextField3.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setToolTipText("");

        jTextField4.setBackground(new java.awt.Color(37, 34, 34));
        jTextField4.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(37, 34, 34));
        jTextField5.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));

        jTextField6.setBackground(new java.awt.Color(37, 34, 34));
        jTextField6.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));

        jTextField7.setBackground(new java.awt.Color(37, 34, 34));
        jTextField7.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));

        jTextField8.setBackground(new java.awt.Color(37, 34, 34));
        jTextField8.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));

        jTextField9.setBackground(new java.awt.Color(37, 34, 34));
        jTextField9.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));

        jTextField10.setBackground(new java.awt.Color(37, 34, 34));
        jTextField10.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jTextField11.setBackground(new java.awt.Color(37, 34, 34));
        jTextField11.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));

        jTextField12.setBackground(new java.awt.Color(37, 34, 34));
        jTextField12.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));

        jTextField13.setBackground(new java.awt.Color(37, 34, 34));
        jTextField13.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));

        jTextField14.setBackground(new java.awt.Color(37, 34, 34));
        jTextField14.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));

        jTextField15.setBackground(new java.awt.Color(37, 34, 34));
        jTextField15.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));

        jTextField16.setBackground(new java.awt.Color(37, 34, 34));
        jTextField16.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("2ο έτος:");

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("3ο έτος:");

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("4ο έτος:");

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("5ο έτος:");

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("6ο έτος:");

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("7ο έτος:");

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("8ο έτος:");

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("9ο έτος:");

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("10ο έτος:");

        jLabel12.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("11ο έτος:");

        jLabel13.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("12ο έτος:");

        jLabel14.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("13ο έτος:");

        jLabel15.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("14ο έτος:");

        jLabel16.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("15ο έτος:");

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout xroniaLayout = new javax.swing.GroupLayout(xronia);
        xronia.setLayout(xroniaLayout);
        xroniaLayout.setHorizontalGroup(
            xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xroniaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(xroniaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(xroniaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(xroniaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(xroniaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(xroniaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(kerdos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addComponent(jLabel11))
                .addGap(37, 37, 37)
                .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(32, 32, 32)
                .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        xroniaLayout.setVerticalGroup(
            xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xroniaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(xroniaLayout.createSequentialGroup()
                        .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kerdos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel8)
                                .addComponent(jLabel13))
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel9)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel15)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel16))
                            .addGroup(xroniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jLabelTitle.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Υπολογισμός Καθαρής Παρούσας Αξίας");

        jButton6.setBackground(new java.awt.Color(37, 34, 34));
        jButton6.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        SecondInvestment.setBackground(new java.awt.Color(37, 34, 34));

        label5.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Αρχικό Κόστος:");

        label2.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Χρόνος:");

        epitokio1.setBackground(new java.awt.Color(37, 34, 34));
        epitokio1.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        epitokio1.setForeground(new java.awt.Color(255, 255, 255));
        epitokio1.setText("Επιτόκιο:");

        arxkostos1.setBackground(new java.awt.Color(37, 34, 34));
        arxkostos1.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        arxkostos1.setForeground(new java.awt.Color(255, 255, 255));
        arxkostos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arxkostos1ActionPerformed(evt);
            }
        });

        arxkostos2.setBackground(new java.awt.Color(37, 34, 34));
        arxkostos2.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        arxkostos2.setForeground(new java.awt.Color(255, 255, 255));
        arxkostos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arxkostos2ActionPerformed(evt);
            }
        });

        jComboBox2.setBackground(new java.awt.Color(37, 34, 34));
        jComboBox2.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        jComboBox2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBox2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SecondInvestmentLayout = new javax.swing.GroupLayout(SecondInvestment);
        SecondInvestment.setLayout(SecondInvestmentLayout);
        SecondInvestmentLayout.setHorizontalGroup(
            SecondInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondInvestmentLayout.createSequentialGroup()
                .addGroup(SecondInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SecondInvestmentLayout.createSequentialGroup()
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SecondInvestmentLayout.createSequentialGroup()
                        .addGroup(SecondInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SecondInvestmentLayout.createSequentialGroup()
                                .addGroup(SecondInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SecondInvestmentLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(epitokio1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(100, 100, 100))
                            .addGroup(SecondInvestmentLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(SecondInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator11)
                                    .addComponent(label5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 102, 102))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SecondInvestmentLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)))
                        .addGroup(SecondInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(arxkostos1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(arxkostos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        SecondInvestmentLayout.setVerticalGroup(
            SecondInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondInvestmentLayout.createSequentialGroup()
                .addGroup(SecondInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SecondInvestmentLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(arxkostos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(SecondInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SecondInvestmentLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SecondInvestmentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(SecondInvestmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SecondInvestmentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(arxkostos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SecondInvestmentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(epitokio1)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        comparison.setBackground(new java.awt.Color(37, 34, 34));
        comparison.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        comparison.setForeground(new java.awt.Color(255, 255, 255));
        comparison.setText("Σύκγριση με 2η επένδυση");
        comparison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comparisonActionPerformed(evt);
            }
        });

        SecondResult.setBackground(new java.awt.Color(37, 34, 34));
        SecondResult.setForeground(new java.awt.Color(255, 255, 255));
        SecondResult.setFont(new java.awt.Font("Book Antiqua", 0, 11)); // NOI18N

        resultButton2.setBackground(new java.awt.Color(34, 34, 37));
        resultButton2.setFont(new java.awt.Font("Book Antiqua", 1, 11)); // NOI18N
        resultButton2.setForeground(new java.awt.Color(255, 255, 255));
        resultButton2.setText("Υπολόγισε");
        resultButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        resultButton2.setBorderPainted(false);
        resultButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        resultButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButton2ActionPerformed(evt);
            }
        });

        result1.setBackground(new java.awt.Color(37, 34, 34));
        result1.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        result1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout SecondResultLayout = new javax.swing.GroupLayout(SecondResult);
        SecondResult.setLayout(SecondResultLayout);
        SecondResultLayout.setHorizontalGroup(
            SecondResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(result1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        SecondResultLayout.setVerticalGroup(
            SecondResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SecondResultLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(SecondResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout npvInsidePanelLayout = new javax.swing.GroupLayout(npvInsidePanel);
        npvInsidePanel.setLayout(npvInsidePanelLayout);
        npvInsidePanelLayout.setHorizontalGroup(
            npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xronia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(npvInsidePanelLayout.createSequentialGroup()
                .addGroup(npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(npvInsidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6)
                        .addGap(125, 125, 125)
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(npvInsidePanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(npvInsidePanelLayout.createSequentialGroup()
                                .addGroup(npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resultButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(npvInsidePanelLayout.createSequentialGroup()
                                        .addGroup(npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(npvInsidePanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(npvInsidePanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(arxkostos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(86, 86, 86)
                                                .addComponent(comparison)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SecondInvestment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(npvInsidePanelLayout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(SecondResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        npvInsidePanelLayout.setVerticalGroup(
            npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, npvInsidePanelLayout.createSequentialGroup()
                .addGroup(npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(npvInsidePanelLayout.createSequentialGroup()
                        .addGroup(npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(arxkostos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(comparison))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SecondInvestment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(xronia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(npvInsidePanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(npvInsidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(result, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(npvInsidePanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(SecondResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        select.add(npvInsidePanel, "card3");

        jLabelPaybackPeriodTEST.setBackground(new java.awt.Color(51, 0, 51));
        jLabelPaybackPeriodTEST.setFont(new java.awt.Font("Book Antiqua", 1, 48)); // NOI18N
        jLabelPaybackPeriodTEST.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPaybackPeriodTEST.setText("jPanel5 inside of jPanel3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPaybackPeriodTEST, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabelPaybackPeriodTEST, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        select.add(jPanel5, "card4");

        jScrollPane2.setBackground(new java.awt.Color(37, 34, 34));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(37, 34, 34));
        jTable1.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(37, 34, 34));
        jTable1.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jTable1.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, testList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${username}"));
        columnBinding.setColumnName("Username");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${arxkostos}"));
        columnBinding.setColumnName("Arxkostos");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${epitokio}"));
        columnBinding.setColumnName("Epitokio");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${xronia}"));
        columnBinding.setColumnName("Xronia");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${result}"));
        columnBinding.setColumnName("Result");
        columnBinding.setColumnClass(Double.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${date}"));
        columnBinding.setColumnName("Date");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${time}"));
        columnBinding.setColumnName("Time");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTable1ComponentAdded(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        select.add(jScrollPane2, "card5");

        getContentPane().add(select, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(37, 35, 35));
        jMenuBar1.setForeground(new java.awt.Color(37, 35, 35));
        jMenuBar1.setFont(new java.awt.Font("Book Antiqua", 1, 11)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setForeground(new java.awt.Color(37, 35, 35));
        jMenu1.setText("Συναρτήσεις");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemNPV.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemNPV.setFont(new java.awt.Font("Book Antiqua", 1, 11)); // NOI18N
        jMenuItemNPV.setForeground(new java.awt.Color(37, 35, 35));
        jMenuItemNPV.setText("Υπολογισμός Καθαρής Παρούσας Αξίας");
        jMenuItemNPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNPVActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNPV);

        jMenuItemPP.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemPP.setFont(new java.awt.Font("Book Antiqua", 1, 11)); // NOI18N
        jMenuItemPP.setForeground(new java.awt.Color(37, 35, 35));
        jMenuItemPP.setText("Υπολογισμός Περιόδου επανείσπραξης");
        jMenuItemPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPPActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPP);

        jMenuItem4.setText("function");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setForeground(new java.awt.Color(37, 35, 35));
        jMenu2.setText("Show Previous Results");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItemNPVprevious.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemNPVprevious.setFont(new java.awt.Font("Book Antiqua", 1, 11)); // NOI18N
        jMenuItemNPVprevious.setForeground(new java.awt.Color(37, 35, 35));
        jMenuItemNPVprevious.setText("Καθαρής Παρούσας Αξίας");
        jMenuItemNPVprevious.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuItemNPVprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNPVpreviousActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemNPVprevious);

        jMenuItemPPprevious.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemPPprevious.setFont(new java.awt.Font("Book Antiqua", 1, 11)); // NOI18N
        jMenuItemPPprevious.setForeground(new java.awt.Color(37, 35, 35));
        jMenuItemPPprevious.setText("Περιόδου Επανείσπραξης");
        jMenuItemPPprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPPpreviousActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPPprevious);

        jMenuItem1.setText("function");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setForeground(new java.awt.Color(37, 35, 35));
        jMenu4.setText("   Details   ");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItemNPVpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNPVpreviousActionPerformed
        select.removeAll();
        select.add(jScrollPane2);
        select.repaint();
        select.revalidate();
        //table t=new table();
        //t.setVisible(true);
        //jPanel6.setVisible(true);
        //jPanel2.setVisible(false);
        //jPanel3.setVisible(false);
        //jPanel1.setVisible(false);
    }//GEN-LAST:event_jMenuItemNPVpreviousActionPerformed

    private void jMenuItemNPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNPVActionPerformed
        //select.setVisible(false);
        //npvInsidePanel.setVisible(true);
        select.removeAll();
        select.add(npvInsidePanel);
        select.repaint();
        select.revalidate();
    }//GEN-LAST:event_jMenuItemNPVActionPerformed

    private void jMenuItemPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPPActionPerformed
        select.removeAll();
        select.add(jPanel5);
        select.repaint();
        select.revalidate();
         /*if(NPVPanel.isBackgroundSet())
            NPVPanel.setVisible(false);
        else
            select.setVisible(false);
        
        PaybackPeriodPanel.setVisible(true);
        */
    }//GEN-LAST:event_jMenuItemPPActionPerformed

    private void resultButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButton1ActionPerformed
        try{
            con=SqlConnect.ConnectDB();//connection
            String kostos = arxkostos.getText();
            String uepitokio=jTextField1.getText();
            String gains=kerdos.getText();
            double athroisma=0;//Δήλωση μεταβλητής & αρχικοποίηση
            double metatropi = (Double.parseDouble(uepitokio)/100);//---Μετατροπή της τιμής που δίνει ο χρήστης για επιτόκιο σε %---//
            //double epitokio1=0;
            // athroisma+=  Double.parseDouble(uposo)/Math.pow(result1,i);
            int k = Integer.parseInt(jComboBox1.getSelectedItem().toString());
            athroisma += (Double.parseDouble(kerdos.getText())/Math.pow((1+metatropi),1));
            System.out.println(Math.pow((1+metatropi),0));

            for(int i=0;i<k-1;i++){//or i=1
                athroisma+=Double.parseDouble(list.get(i).getText())/Math.pow((1+metatropi),i+2);//or i+1
                System.out.println(Math.pow((1+metatropi),i+2));//or i+1
            }//for athroisma
            result.setText(String.valueOf(athroisma-Double.parseDouble(kostos)));
            /* if(uposo.length()==0||uepitokio.length()==0||uarxep.length()==0){
                JOptionPane.showMessageDialog(null,"You have to fill in all the fields!");
            }Για να μην είναι κενά τα πεδία*/

            //result= Double.parseDouble(new DecimalFormat("##.####").format(result));
            //DecimalFormat df= new DecimalFormat(".##");
            //String dx=df.format(result);
            //result=Double.valueOf(dx);

            //--------Εμφάνιση μηνύματος ανάλογα με το αποτέλεσμα--------//
            if(Double.parseDouble(result.getText())> 0)
                JOptionPane.showMessageDialog(null, "The investment will make profits.");
            else if(Double.parseDouble(result.getText()) == 0)
                JOptionPane.showMessageDialog(null, "The investment will neither make profits nor damages.");
            else
                JOptionPane.showMessageDialog(null, "Thw investment will have only expences");
            
            //------------------CODE FROM NPVFinal----------------------//
             System.out.println("Before insert into\n");
             String npvquery="INSERT INTO test (username,arxkostos,epitokio,xronia,result) VALUES (?,?,?,?,?) ";
             System.out.println("After insert into the username= \n"+username);
             pst=con.prepareStatement(npvquery);
             System.out.println("After prepareStatement\n");
             System.out.println("mphke");
             pst.setString(1,username);
             pst.setString(2, arxkostos.getText());
             pst.setString(3, jTextField1.getText());
             pst.setInt(4, k);
             pst.setString(5, result.getText());
             System.out.println("Vghke");
             pst.executeUpdate();
             /*-----update jtable-----//
             String viewUser="Select * from test where username=?"+username;
             pst=con.prepareStatement(viewUser);
             jTable1.updateUI();
             jTable1.validate();
             */
             pst.close();
             con.close();
            
            //insert the results into a jtable in another jFrame(epilogi)
            
           /*
            DefaultTableModel model=(DefaultTableModel)jTableResults.getModel(); //new DefaultTableModel();
           model.addColumn(NORMAL);
           
           String npvquery = "insert into dataResults (arxkostos, epitokio, xronos, 1o etos, 2o etos, 3o etos, 4o etos, 5o etos, 6o etos, 7o etos, 8o etos, 9o etos, 10o etos, 11o etos, 12o etos, 13o etos, 14o etos, 15o etos) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
           PreparedStatement npv=con.prepareStatement(npvquery);
           
           npv.setString(1, arxkostos.getText());
           npv.setString(2, jTextField1.getText());
           npv.setString(3, kerdos.getText());
           npv.setString(4, jTextField3.getText());
           npv.setString(5, jTextField4.getText());
           npv.setString(6, jTextField5.getText());
           npv.setString(7, jTextField6.getText());
           npv.setString(8, jTextField7.getText());
           npv.setString(9, jTextField8.getText());
           npv.setString(10, jTextField9.getText());
           npv.setString(11, jTextField10.getText());
           npv.setString(12, jTextField11.getText());
           npv.setString(13, jTextField12.getText());
           npv.setString(14, jTextField13.getText());
           npv.setString(15, jTextField14.getText());
           npv.setString(16, jTextField15.getText());
           npv.setString(17, jTextField16.getText());
           
           rs=npv.executeQuery();
           */
        }//try
        catch(Exception e){
            System.out.println(e.getMessage());
        }//catch
    }//GEN-LAST:event_resultButton1ActionPerformed

    private void arxkostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arxkostosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arxkostosActionPerformed

    private void jComboBox1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1AncestorAdded

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        /*jComboBox1.addItemListener(new ItemListenertener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if(e.getStateChange() == ItemEvent.SELECTED) {
                    kerdos.setText((String) jComboBox1.getSelectedItem());
                }
            }
        }*/
        //-----------------------------------------------------------------------//
        System.out.println(jComboBox1.getSelectedItem().toString());
        int k = Integer.parseInt(jComboBox1.getSelectedItem().toString());//η επιλογή του χρήστη γίνεται parseInt και αποθηκεύεται στην μεταβλητή k

        //-----------------visible τα jTextField & jLabel ανάλογα με την επιλογή του χρήστη---------------//
        for(int i=0;i<k-1;i++){
            list.get(i).setVisible(true);
            LabelList.get(i).setVisible(true);
            //---------------------------------------------------------------//
            if(Integer.parseInt(jComboBox1.getSelectedItem().toString())>5)
            jSeparator7.setVisible(true);

            if(Integer.parseInt(jComboBox1.getSelectedItem().toString())>10)
            jSeparator6.setVisible(true);

        }
        //-----------------unvisible τα jTextField & jLabel ανάλογα με την επιλογή του χρήστη---------------//
        for(int i=k-1;i<list.size();i++){
            list.get(i).setVisible(false);
            LabelList.get(i).setVisible(false);
            //-----------------------------------------------------------//
            if(Integer.parseInt(jComboBox1.getSelectedItem().toString())<6)
            jSeparator7.setVisible(false);

            if(Integer.parseInt(jComboBox1.getSelectedItem().toString())<11)
            jSeparator6.setVisible(false);

        }

        this.validate();//ανανέωση του window
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //-----------------------------------------------------//
        //deuteri_selida w=new deuteri_selida();//δημιουργια αντικειμενου deuteri_selida
        //w.setVisible(true);
        //dispose();//κλείσιμο παρόντως window(NetPresentValue)
        select.removeAll();
        select.add(Details);
        select.repaint();
        select.revalidate();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void arxkostos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arxkostos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arxkostos1ActionPerformed

    private void arxkostos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arxkostos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arxkostos2ActionPerformed

    private void jComboBox2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2AncestorAdded

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        System.out.println(jComboBox2.getSelectedItem().toString());
        int k = Integer.parseInt(jComboBox2.getSelectedItem().toString());//η επιλογή του χρήστη γίνεται parseInt και αποθηκεύεται στην μεταβλητή k

        //-----------------visible τα jTextField & jLabel ανάλογα με την επιλογή του χρήστη---------------//
        for(int i=0;i<k-1;i++){
            list.get(i).setVisible(true);
            LabelList.get(i).setVisible(true);
            //---------------------------------------------------------------//
            if(Integer.parseInt(jComboBox2.getSelectedItem().toString())>5)
            jSeparator7.setVisible(true);

            if(Integer.parseInt(jComboBox2.getSelectedItem().toString())>10)
            jSeparator6.setVisible(true);

        }
        //-----------------unvisible τα jTextField & jLabel ανάλογα με την επιλογή του χρήστη---------------//
        for(int i=k-1;i<list.size();i++){
            list.get(i).setVisible(false);
            LabelList.get(i).setVisible(false);
            //-----------------------------------------------------------//
            if(Integer.parseInt(jComboBox2.getSelectedItem().toString())<6)
            jSeparator7.setVisible(false);

            if(Integer.parseInt(jComboBox2.getSelectedItem().toString())<11)
            jSeparator6.setVisible(false);

        }

        this.validate();//ανανέωση του window
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void comparisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comparisonActionPerformed
        //όταν ο χρήστης επιλέξει ότι θέλει σύγκριση με 2η επένδυση
        //αρχικοποιούνται τα πεδία που βάζειτα μελλοντικά κέρδη
        //if(result.getText()!=null || result.getText()!=""){//να βγεί πρώτα το αποτέλεσμα για την 1η επένδυση
            if(comparison.isSelected()==true){
                select.validate();
                npvInsidePanel.setVisible(true);
                jPanel5.setVisible(true);
                //jPanel3.paintComponents(g);

                //jPanel3.revalidate();
                //jPanel3.setVisible(false);
                //jPanel3.setVisible(true);
                int arxikopoihsh = Integer.parseInt(jComboBox2.getSelectedItem().toString());//epilogh xronwn apo ton xrhsth
                //int arxikopoihsh=15;
                for(int i=arxikopoihsh-1;i<list.size();i++){
                    list.get(i).setVisible(false);
                    list.get(i).setText("");
                    //jTextField(i).setText("");
                    LabelList.get(i).setVisible(false);
                    jSeparator7.setVisible(false);
                    jSeparator6.setVisible(false);
                    kerdos.setText("");
                    //result.setText("");
                    //for(int t=3;t<16;t++)
                    //list.get(t).setText("");

                }//for

                this.validate();
            }//if
            else if(comparison.isSelected()==false){
                npvInsidePanel.setVisible(false);
                jPanel5.setVisible(false);
                arxkostos2.setText("");//arxiko kostos gia 2h ependush
                arxkostos1.setText("");//epitokio gia 2h ependush
            }//else if
            //}//if
        /*
        int arxikopoihsh = Integer.parseInt(jComboBox2.getSelectedItem().toString());
        //int arxikopoihsh=15;
        for(int i=arxikopoihsh-1;i<list.size();i++){
            list.get(i).setVisible(false);
            list.get(i).setText("");
            //jTextField(i).setText("");
            LabelList.get(i).setVisible(false);
            jSeparator7.setVisible(false);
            jSeparator6.setVisible(false);
            kerdos.setText("");
            result.setText("");
            //for(int t=3;t<16;t++)
            //list.get(t).setText("");

        }//for
        this.validate();
        //jPanel3.repaint();//αφαιρει ολα τα components
        //jPanel3 panel=new jPanel3(new BorderLayout());
        */
    }//GEN-LAST:event_comparisonActionPerformed

    private void resultButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String kostos = arxkostos2.getText();
            String uepitokio=arxkostos1.getText();
            String gains=kerdos.getText();//η default πρωτη τιμή πιθανου κερδους
            double athroisma=0;//Δήλωση μεταβλητής & αρχικοποίηση
            double metatropi = (Double.parseDouble(uepitokio)/100);//---Μετατροπή της τιμής που δίνει ο χρήστης για επιτόκιο σε %---//
            //double epitokio1=0;
            // athroisma+=  Double.parseDouble(uposo)/Math.pow(result1,i);
            int k = Integer.parseInt(jComboBox2.getSelectedItem().toString());
            athroisma += (Double.parseDouble(kerdos.getText())/Math.pow((1+metatropi),1));
            System.out.println(Math.pow((1+metatropi),0));

            for(int i=0;i<k-1;i++){//or i=1
                athroisma+=Double.parseDouble(list.get(i).getText())/Math.pow((1+metatropi),i+2);//or i+1
                System.out.println(Math.pow((1+metatropi),i+2));//or i+1
            }
            result1.setText(String.valueOf(athroisma-Double.parseDouble(kostos)));

            //------------------------Εμφάνιση ανάλογα με το αποτέλεσμα-------------------------//
            //---------------------------Σύγκριση με την 1η επένδυση----------------------------//
            if(Double.parseDouble(result1.getText()) > Double.parseDouble(result.getText()) && Double.parseDouble(result1.getText()) > 0)
            JOptionPane.showMessageDialog(null, "The second investment will gain more money.");
            else if(Double.parseDouble(result1.getText()) == Double.parseDouble(result.getText()))
            JOptionPane.showMessageDialog(null, "The investment will gain equal money.");
            else
            JOptionPane.showMessageDialog(null, "The first investment is the best.");

        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_resultButton2ActionPerformed

    private void jMenuItemPPpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPPpreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPPpreviousActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        select.removeAll();
        select.add(Details);
        select.repaint();
        select.revalidate();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jTable1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTable1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentAdded

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(epilogi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(epilogi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(epilogi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(epilogi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new epilogi1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Details;
    private javax.swing.JLabel NPV;
    private javax.swing.JPanel SecondInvestment;
    private javax.swing.JPanel SecondResult;
    private java.awt.TextField arxkostos;
    private java.awt.TextField arxkostos1;
    private java.awt.TextField arxkostos2;
    private javax.swing.JPanel basicDetails;
    private javax.swing.JPanel basicDetailsNPV;
    private javax.swing.JPanel basicDetailsPP;
    private javax.swing.JSeparator basicSeparator1;
    private javax.swing.JCheckBox comparison;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel epitokio;
    private javax.swing.JLabel epitokio1;
    private javax.swing.JLabel function3;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPaybackPeriodTEST;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemNPV;
    private javax.swing.JMenuItem jMenuItemNPVprevious;
    private javax.swing.JMenuItem jMenuItemPP;
    private javax.swing.JMenuItem jMenuItemPPprevious;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField kerdos;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JPanel moreDetails;
    private javax.swing.JPanel moreDetailsNPV;
    private javax.swing.JPanel moreDetailsPP;
    private javax.swing.JPanel npvInsidePanel;
    private javax.swing.JLabel paybackPeriod;
    private java.awt.TextField result;
    private java.awt.TextField result1;
    private javax.swing.JButton resultButton1;
    private javax.swing.JButton resultButton2;
    private javax.swing.JPanel select;
    private java.util.List<testTable.Test> testList;
    private javax.persistence.Query testQuery;
    private javax.swing.JPanel xronia;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
